name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - master   # или main, если у вас основная ветка main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Клонируем репозиторий вместе с сабмодулями (ToDo.Shared)
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # 2) Устанавливаем .NET 8 SDK
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          include-prerelease: true

      # 3) (опционально) Убедимся, что csproj-файлы на месте
      - name: List all .csproj files
        run: find . -type f -name '*.csproj'

      # 4) Restore & Publish Frontend
      - name: Restore & Publish Frontend
        run: |
          proj="ToDo.Frontend/ToDo.Frontend.csproj"
          echo "Restoring $proj"
          dotnet restore "$proj"
          echo "Publishing $proj"
          dotnet publish "$proj" -c Release -o "ToDo.Frontend/release"

      # 5) (опционально) Проверяем содержимое папки release
      - name: Inspect publish folder
        run: find ToDo.Frontend/release -type f

      # 6) Деплойим на ветку gh-pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: ToDo.Frontend/release
          clean: true
