name: Deploy Blazor WASM to GitHub Pages (Windows)

on:
  push:
    branches:
      - master   # или main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          include-prerelease: true

      - name: Find all .csproj files (debug)
        shell: pwsh
        run: |
          Write-Host "→ .csproj files in repo:"
          Get-ChildItem -Path . -Filter '*.csproj' -Recurse | ForEach-Object FullName

      - name: Publish Frontend
        shell: pwsh
        working-directory: 'ToDo.Frontend'
        run: dotnet publish -c Release --output release --nologo

      - name: Inspect publish folder (debug)
        shell: pwsh
        run: |
          Write-Host "→ release folder contents:"
          Get-ChildItem -Path ToDo.Frontend\release -Recurse

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          # Скорректируйте этот путь после того, как увидите, где лежит ваш index.html
          folder: ToDo.Frontend\release
