name: Deploy Blazor WASM to GitHub Pages (Windows)

on:
  push:
    branches:
      - master   # или main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # 1) Клонируем репозиторий вместе с сабмодулями (ToDo.Shared)
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # 2) Устанавливаем .NET SDK
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          include-prerelease: true

      # 3) Восстанавливаем зависимости и публикуем проект по его пути
      - name: Restore & Publish Frontend
        shell: pwsh
        run: |
          # Убедитесь, что путь точно совпадает с тем, что вы видели в List all .csproj files
          $proj = 'ToDo.Frontend/ToDo.Frontend/ToDo.Frontend.csproj'
          dotnet restore $proj
          dotnet publish  $proj -c Release --output ToDo.Frontend/ToDo.Frontend/release

      # 4) (опционально) Инспекция результата
      - name: Inspect publish folder
        shell: pwsh
        run: Get-ChildItem -Recurse -Path ToDo.Frontend/ToDo.Frontend/release

      # 5) Деплойим на gh-pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: ToDo.Frontend/ToDo.Frontend/release
          clean: true
